--!native
--!strict
--!optimize 2

--[[
                                                                                                                                              
                  πππππππππππππππππππ                                                         πππ     ∞√                                              
                  +++-÷≠√π++×√√≠×+++÷                                  ππ                 √-+×≠ππ≈×+++×π                                              
                  +×√    ≠++≠    π+×π                               ≈×+×                 ≠++≠      √++≠                                               
                 ≈=      ++-π     ≠≈           ×+=                  √++≈                √-++        ≠-√                                               
                 =      ≈++=      ≈           ≈++÷                  ≠+-                 ≈+++        π÷                                                
                ∞       -++√      ≠            ππ                   -+≠                 π×++÷        ≈                                                
                       √++÷                                        ∞++                   ∞+++÷                                                        
                       =++√   ∞-+≈   ∞×+×   ≈--π   π÷-×   ≠×--∞    ÷+÷      √÷×≠≠÷π       √+++-√            ≈×÷≈==       =÷≠÷×∞                       
                      π-+-   ≈ ÷++  ≠π=++≠π≠π÷+=  ∞∞∞-+∞=∞   ×+≠  √-+π    =+≈    ≠×         ×+++≠         --√    +÷   ∞+=   ≈++√                      
                      ≠++∞  √  -+≠π≠  π≠π √ π-+π π  ≈++-     ≠+×  ≠+×   √-×     ∞-≈          ∞++++      ≠+=     =+π  ÷+π    ≠+÷                       
                      ÷+-     ∞++∞=         ≠+×     ÷+-      ÷+× π×+√  √+=     ≠×√            π×+++√   =+≈    π÷÷   ÷-π                               
                     ∞++≈     ÷++=          ÷+∞    ∞-+π      -+= ∞+-   +×π  √=÷π     ∞          ×+++  ≈+=   ∞=≠    =+∞                                
                     =++     √-+×          ∞+-     =+=      ≠++π ÷+≠  ÷+÷≈∞π         =          √-++ππ-+≠≈∞π      √+×                                 
                    √++=     ≠++           =+≠    π-+π     √-+≠ √+-π  +-∞            -π          ×+- ∞+÷          =+=                                 
                    =++√    π×+≈          √++π  ≈ ≈+÷     π×+≠  ≠+=  ≠++∞       ∞√  ≈+=         π-+π ∞+×        ≠ =+÷       π∞                        
                   π++×     ∞+-           ≈+÷π≈∞  ×+-    ∞--∞   -+≈ ≠ =+×     π≠    ×++÷π      √-×   π×+≠     ∞∞  π++∞     ≈√                         
                π≈÷++++÷∞   =+≈           √++=   √+×∞=÷×-×∞     =+-∞   ∞×+××÷≠π     ≠  ∞÷××÷÷×÷≈       ≠--×÷÷≈     π=+-××=∞                           
                                                 ÷+≠                                                                                                  
                                                 +-√                                                                                                  
                                                ≠+÷                                                                                                   
                                               π++≠                                                                                                   
                                              ≈====√                                                                                                  


Welcome to your very own (not transpiled) comprehensive, government-grade encryption library with
Veracrypt-equivalent security in Roblox Luau!

This module features:
	- Multiple ciphers: AES, Serpent, Twofish (all 256b)
	- Multiple hash functions: SHA-256, SHA-512, Whirlpool
	- Key derivation: PBKDF2 with configurable iterations (the default is 500,000)
	- XTS mode for disk/volume encryption, implemented to IEEE P1619
	- Cryptographically secure* random number generation
	
This module is the result of countless hours of effort. I ask that you only give credit where it is due.

Sincerely, @stlxvy
]]

return require(script.Parent.TripleSec)